name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-6.1.0-ruby-3.0.0-${{ hashFiles('**/Gemfile.lock') }}
    - name: Build and test with Rake
      run: |
        bundle config path vendor/bundle
        bundle update
        bundle exec rake
      env:
        RAILS_VERSION: 6.1.0
